// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createIdentity = `-- name: CreateIdentity :one
insert into identities (user_id, provider_id, provider_uid, password_digest)
select 
  u.user_id,
  p.provider_id,
  ?1,
  ?2
from users u
join providers p on lower(?3) = p.name
where u.uuid = ?4
returning
  (select u.uuid from users u where u.user_id = user_id) as user_uuid,
  (select name from providers p where p.provider_id = provider_id) as provider,
  provider_uid,
  password_digest
`

type CreateIdentityParams struct {
	ProviderUid    *string   `json:"providerUid"`
	PasswordDigest *string   `json:"passwordDigest"`
	Provider       string    `json:"provider"`
	UserUuid       uuid.UUID `json:"id"`
}

type CreateIdentityRow struct {
	Uuid           uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	ProviderUid    *string   `json:"providerUid"`
	PasswordDigest *string   `json:"passwordDigest"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (CreateIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, createIdentity,
		arg.ProviderUid,
		arg.PasswordDigest,
		arg.Provider,
		arg.UserUuid,
	)
	var i CreateIdentityRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.ProviderUid,
		&i.PasswordDigest,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, uuid, is_admin)
values (lower(?1), ?2, ?3)
returning uuid,
  email
`

type CreateUserParams struct {
	Email   string    `json:"email"`
	Uuid    uuid.UUID `json:"id"`
	IsAdmin bool      `json:"isAdmin"`
}

type CreateUserRow struct {
	Uuid  uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Uuid, arg.IsAdmin)
	var i CreateUserRow
	err := row.Scan(&i.Uuid, &i.Email)
	return i, err
}

const getAdminCount = `-- name: GetAdminCount :one
select count(1)
from users
where is_admin = true
`

func (q *Queries) GetAdminCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAdminCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getIdentityByEmail = `-- name: GetIdentityByEmail :one
select 
  u.uuid as user_uuid,
  p.name as provider,
  i.provider_uid,
  i.password_digest
from identities i
join users u on u.user_id = i.user_id
join providers p on p.provider_id = i.provider_id
where u.email = lower(?1)
  and p.name = ?2
`

type GetIdentityByEmailParams struct {
	Email    string `json:"email"`
	Provider string `json:"provider"`
}

type GetIdentityByEmailRow struct {
	UserUuid       uuid.UUID `json:"id"`
	Provider       string    `json:"provider"`
	ProviderUid    *string   `json:"providerUid"`
	PasswordDigest *string   `json:"passwordDigest"`
}

func (q *Queries) GetIdentityByEmail(ctx context.Context, arg GetIdentityByEmailParams) (GetIdentityByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByEmail, arg.Email, arg.Provider)
	var i GetIdentityByEmailRow
	err := row.Scan(
		&i.UserUuid,
		&i.Provider,
		&i.ProviderUid,
		&i.PasswordDigest,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
select uuid,
  email,
  is_admin
from users
where uuid = ?1
`

type GetUserRow struct {
	Uuid    uuid.UUID `json:"id"`
	Email   string    `json:"email"`
	IsAdmin bool      `json:"isAdmin"`
}

func (q *Queries) GetUser(ctx context.Context, argUuid uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, argUuid)
	var i GetUserRow
	err := row.Scan(&i.Uuid, &i.Email, &i.IsAdmin)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select uuid,
  email,
  is_admin
from users
where email = lower(?1)
`

type GetUserByEmailRow struct {
	Uuid    uuid.UUID `json:"id"`
	Email   string    `json:"email"`
	IsAdmin bool      `json:"isAdmin"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.Uuid, &i.Email, &i.IsAdmin)
	return i, err
}
