// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cell_textures.sql

package database

import (
	"context"
)

const createCellTexture = `-- name: CreateCellTexture :one
insert into cell_textures (key, display_name)
values (lower(?1), ?2)
returning key,
  display_name,
  created_at,
  updated_at
`

type CreateCellTextureParams struct {
	Key         string `json:"key"`
	DisplayName string `json:"displayName"`
}

type CreateCellTextureRow struct {
	Key         string `json:"key"`
	DisplayName string `json:"displayName"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

func (q *Queries) CreateCellTexture(ctx context.Context, arg CreateCellTextureParams) (CreateCellTextureRow, error) {
	row := q.db.QueryRowContext(ctx, createCellTexture, arg.Key, arg.DisplayName)
	var i CreateCellTextureRow
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCellTexture = `-- name: GetCellTexture :one
select key, display_name, created_at, updated_at
from cell_textures
where key = ? and is_deleted = false
`

type GetCellTextureRow struct {
	Key         string `json:"key"`
	DisplayName string `json:"displayName"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

func (q *Queries) GetCellTexture(ctx context.Context, key string) (GetCellTextureRow, error) {
	row := q.db.QueryRowContext(ctx, getCellTexture, key)
	var i GetCellTextureRow
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hardDeleteCellTexture = `-- name: HardDeleteCellTexture :one
delete from cell_textures
where key = ?
returning key,
  display_name,
  created_at,
  updated_at
`

type HardDeleteCellTextureRow struct {
	Key         string `json:"key"`
	DisplayName string `json:"displayName"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

func (q *Queries) HardDeleteCellTexture(ctx context.Context, key string) (HardDeleteCellTextureRow, error) {
	row := q.db.QueryRowContext(ctx, hardDeleteCellTexture, key)
	var i HardDeleteCellTextureRow
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCellTextures = `-- name: ListCellTextures :many
select key, display_name, created_at, updated_at
from cell_textures
where is_deleted = false
order by created_at desc
`

type ListCellTexturesRow struct {
	Key         string `json:"key"`
	DisplayName string `json:"displayName"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

func (q *Queries) ListCellTextures(ctx context.Context) ([]ListCellTexturesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCellTextures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCellTexturesRow
	for rows.Next() {
		var i ListCellTexturesRow
		if err := rows.Scan(
			&i.Key,
			&i.DisplayName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCellTexture = `-- name: SoftDeleteCellTexture :one
update cell_textures
set updated_at = unixepoch(),
  is_deleted = true
where key = ?
returning key,
  display_name,
  created_at,
  updated_at
`

type SoftDeleteCellTextureRow struct {
	Key         string `json:"key"`
	DisplayName string `json:"displayName"`
	CreatedAt   int64  `json:"createdAt"`
	UpdatedAt   int64  `json:"updatedAt"`
}

func (q *Queries) SoftDeleteCellTexture(ctx context.Context, key string) (SoftDeleteCellTextureRow, error) {
	row := q.db.QueryRowContext(ctx, softDeleteCellTexture, key)
	var i SoftDeleteCellTextureRow
	err := row.Scan(
		&i.Key,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
