// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :one
insert into games (uuid, name, is_active, user_id, game_data_uuid)
select 
  ?1, 
  ?2, 
  ?3, 
  u.user_id, 
  ?4 
from users u
where u.uuid = ?5
returning 
  uuid, 
  name, 
  created_at,
  updated_at,
  is_active
`

type CreateGameParams struct {
	Uuid         uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	IsActive     bool      `json:"isActive"`
	GameDataUuid uuid.UUID `json:"id"`
	UserUuid     uuid.UUID `json:"id"`
}

type CreateGameRow struct {
	Uuid      uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt int64     `json:"createdAt"`
	UpdatedAt int64     `json:"updatedAt"`
	IsActive  bool      `json:"isActive"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (CreateGameRow, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Uuid,
		arg.Name,
		arg.IsActive,
		arg.GameDataUuid,
		arg.UserUuid,
	)
	var i CreateGameRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}

const getGame = `-- name: GetGame :one
select
  g.uuid,
  g.name,
  g.created_at,
  g.updated_at,
  g.is_active
from games g
join players p on g.game_id = p.game_id
join users u on u.uuid = ?1
where g.uuid = ?2
`

type GetGameParams struct {
	UserUuid uuid.UUID `json:"id"`
	Uuid     uuid.UUID `json:"id"`
}

type GetGameRow struct {
	Uuid      uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt int64     `json:"createdAt"`
	UpdatedAt int64     `json:"updatedAt"`
	IsActive  bool      `json:"isActive"`
}

func (q *Queries) GetGame(ctx context.Context, arg GetGameParams) (GetGameRow, error) {
	row := q.db.QueryRowContext(ctx, getGame, arg.UserUuid, arg.Uuid)
	var i GetGameRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsActive,
	)
	return i, err
}
