// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: levels.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLevel = `-- name: CreateLevel :one
insert into levels (uuid, name, user_id)
select 
  ?1,
  ?2,
  u.user_id
from users u
where u.uuid = ?3
returning
  uuid,
  name,
  created_at,
  updated_at
`

type CreateLevelParams struct {
	Uuid     uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	UserUuid uuid.UUID `json:"id"`
}

type CreateLevelRow struct {
	Uuid      uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt int64     `json:"createdAt"`
	UpdatedAt int64     `json:"updatedAt"`
}

func (q *Queries) CreateLevel(ctx context.Context, arg CreateLevelParams) (CreateLevelRow, error) {
	row := q.db.QueryRowContext(ctx, createLevel, arg.Uuid, arg.Name, arg.UserUuid)
	var i CreateLevelRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLevel = `-- name: GetLevel :one
select
  l.uuid,
  l.name,
  l.created_at,
  l.updated_at
from levels l
join users u
  on l.user_id = u.user_id
where u.uuid = ?1
  and l.uuid = ?2
  and l.is_deleted = false
`

type GetLevelParams struct {
	UserUuid  uuid.UUID `json:"id"`
	LevelUuid uuid.UUID `json:"id"`
}

type GetLevelRow struct {
	Uuid      uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt int64     `json:"createdAt"`
	UpdatedAt int64     `json:"updatedAt"`
}

func (q *Queries) GetLevel(ctx context.Context, arg GetLevelParams) (GetLevelRow, error) {
	row := q.db.QueryRowContext(ctx, getLevel, arg.UserUuid, arg.LevelUuid)
	var i GetLevelRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLevels = `-- name: ListLevels :many
select
  l.uuid,
  l.name,
  l.created_at,
  l.updated_at
from levels l
join users u
  on l.user_id = u.user_id
where u.uuid = ?1
  and l.is_deleted = false
`

type ListLevelsRow struct {
	Uuid      uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt int64     `json:"createdAt"`
	UpdatedAt int64     `json:"updatedAt"`
}

func (q *Queries) ListLevels(ctx context.Context, userUuid uuid.UUID) ([]ListLevelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLevels, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLevelsRow
	for rows.Next() {
		var i ListLevelsRow
		if err := rows.Scan(
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLevel = `-- name: UpdateLevel :one
update levels
set name = ?1,
  updated_at = unixepoch()
where levels.uuid = ?2
  and exists (
    select 1
    from users u
    where levels.user_id = u.user_id
      and u.uuid = ?3
  )
returning
  uuid,
  name,
  created_at,
  updated_at
`

type UpdateLevelParams struct {
	Name      string    `json:"name"`
	LevelUuid uuid.UUID `json:"id"`
	UserUuid  uuid.UUID `json:"id"`
}

type UpdateLevelRow struct {
	Uuid      uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt int64     `json:"createdAt"`
	UpdatedAt int64     `json:"updatedAt"`
}

func (q *Queries) UpdateLevel(ctx context.Context, arg UpdateLevelParams) (UpdateLevelRow, error) {
	row := q.db.QueryRowContext(ctx, updateLevel, arg.Name, arg.LevelUuid, arg.UserUuid)
	var i UpdateLevelRow
	err := row.Scan(
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
