// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
)

type CellTexture struct {
	CellTextureID int64  `json:"cellTextureId"`
	Key           string `json:"key"`
	DisplayName   string `json:"displayName"`
	CreatedAt     int64  `json:"createdAt"`
	UpdatedAt     int64  `json:"updatedAt"`
	IsDeleted     bool   `json:"isDeleted"`
}

type Game struct {
	GameID       int64     `json:"gameId"`
	Uuid         uuid.UUID `json:"id"`
	CreatedAt    int64     `json:"createdAt"`
	UpdatedAt    int64     `json:"updatedAt"`
	IsActive     bool      `json:"isActive"`
	Name         string    `json:"name"`
	UserID       int64     `json:"userId"`
	GameDataUuid uuid.UUID `json:"id"`
}

type Identity struct {
	IdentityID     int64   `json:"identityId"`
	UserID         int64   `json:"userId"`
	PasswordDigest *string `json:"passwordDigest"`
	ProviderUid    *string `json:"providerUid"`
	ProviderID     int64   `json:"providerId"`
}

type Level struct {
	LevelID   int64     `json:"levelId"`
	Uuid      uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	UserID    *int64    `json:"userId"`
	CreatedAt int64     `json:"createdAt"`
	UpdatedAt int64     `json:"updatedAt"`
	IsDeleted bool      `json:"isDeleted"`
}

type Player struct {
	PlayerID        int64     `json:"playerId"`
	Uuid            uuid.UUID `json:"id"`
	GameID          int64     `json:"gameId"`
	UserID          int64     `json:"userId"`
	PermissionLevel string    `json:"permissionLevel"`
}

type Profile struct {
	ProfileID int64   `json:"profileId"`
	UserID    int64   `json:"userId"`
	Username  string  `json:"username"`
	Avatar    *string `json:"avatar"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
}

type Provider struct {
	ProviderID int64  `json:"providerId"`
	Name       string `json:"name"`
}

type User struct {
	UserID            int64     `json:"userId"`
	Uuid              uuid.UUID `json:"id"`
	Email             string    `json:"email"`
	IsAdmin           bool      `json:"isAdmin"`
	PrimaryIdentityID *int64    `json:"primaryIdentityId"`
}
