// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createGameMaster = `-- name: CreateGameMaster :one
insert into players (uuid, game_id, user_id, permission_level)
select
  ?1,
  g.game_id,
  u.user_id,
  'game_master'
from games g
join users u on u.uuid = ?2
where g.uuid = ?3
returning
  uuid,
  permission_level
`

type CreateGameMasterParams struct {
	Uuid     uuid.UUID `json:"id"`
	UserUuid uuid.UUID `json:"id"`
	GameUuid uuid.UUID `json:"id"`
}

type CreateGameMasterRow struct {
	Uuid            uuid.UUID `json:"id"`
	PermissionLevel string    `json:"permissionLevel"`
}

func (q *Queries) CreateGameMaster(ctx context.Context, arg CreateGameMasterParams) (CreateGameMasterRow, error) {
	row := q.db.QueryRowContext(ctx, createGameMaster, arg.Uuid, arg.UserUuid, arg.GameUuid)
	var i CreateGameMasterRow
	err := row.Scan(&i.Uuid, &i.PermissionLevel)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one
insert into players (uuid, game_id, user_id, permission_level)
select
  ?1,
  g.game_id,
  u.user_id,
  ?2
from games g
join users u on u.uuid = ?3
where g.uuid = ?4
and exists (
  select 1 
  from players p 
  join users gm on p.user_id = gm.user_id 
  where gm.uuid = ?5 
  and p.permission_level = 'game_master'
)
returning
  uuid,
  permission_level
`

type CreatePlayerParams struct {
	Uuid            uuid.UUID `json:"id"`
	PermissionLevel string    `json:"permissionLevel"`
	UserUuid        uuid.UUID `json:"id"`
	GameUuid        uuid.UUID `json:"id"`
	CreatorUuid     uuid.UUID `json:"id"`
}

type CreatePlayerRow struct {
	Uuid            uuid.UUID `json:"id"`
	PermissionLevel string    `json:"permissionLevel"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayer,
		arg.Uuid,
		arg.PermissionLevel,
		arg.UserUuid,
		arg.GameUuid,
		arg.CreatorUuid,
	)
	var i CreatePlayerRow
	err := row.Scan(&i.Uuid, &i.PermissionLevel)
	return i, err
}

const getPlayer = `-- name: GetPlayer :one
select
  p.uuid,
  permission_level
from players p
join users u on p.user_id = u.user_id
join games g on p.game_id = g.game_id
where u.uuid = ?1
  and g.uuid = ?2
`

type GetPlayerParams struct {
	UserUuid uuid.UUID `json:"id"`
	GameUuid uuid.UUID `json:"id"`
}

type GetPlayerRow struct {
	Uuid            uuid.UUID `json:"id"`
	PermissionLevel string    `json:"permissionLevel"`
}

func (q *Queries) GetPlayer(ctx context.Context, arg GetPlayerParams) (GetPlayerRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayer, arg.UserUuid, arg.GameUuid)
	var i GetPlayerRow
	err := row.Scan(&i.Uuid, &i.PermissionLevel)
	return i, err
}
