// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getProfile = `-- name: GetProfile :one
select p.username,
  p.avatar,
  p.created_at,
  p.updated_at
from users u
join profiles p
  on u.user_id = p.user_id
where u.uuid = ?1
`

type GetProfileRow struct {
	Username  string  `json:"username"`
	Avatar    *string `json:"avatar"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
}

func (q *Queries) GetProfile(ctx context.Context, userUuid uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getProfile, userUuid)
	var i GetProfileRow
	err := row.Scan(
		&i.Username,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
insert into profiles (user_id, username, avatar)
select u.user_id, ?1, ?2
from users u
where u.uuid = ?3
on conflict (user_id)
  do update set username = excluded.username, avatar = excluded.avatar
returning
  username,
  avatar,
  created_at,
  updated_at
`

type UpsertProfileParams struct {
	Username string    `json:"username"`
	Avatar   *string   `json:"avatar"`
	UserUuid uuid.UUID `json:"id"`
}

type UpsertProfileRow struct {
	Username  string  `json:"username"`
	Avatar    *string `json:"avatar"`
	CreatedAt int64   `json:"createdAt"`
	UpdatedAt int64   `json:"updatedAt"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRowContext(ctx, upsertProfile, arg.Username, arg.Avatar, arg.UserUuid)
	var i UpsertProfileRow
	err := row.Scan(
		&i.Username,
		&i.Avatar,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
