services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      # an enterprising hoster would share all these environment variables
      POSTGRES_DB: opendungeon
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  s3:
    image: chrislusf/seaweedfs:latest
    ports:
      - 8333:8333 # S3
      - 9333:9333 # Master
      - 8888:8888 # filer
    entrypoint: weed
    command: "mini -dir=/var/s3/data -ip=localhost"
    volumes:
      - s3_data:/var/s3/data
      - s3_filer:/data
    environment:
      AWS_ACCESS_KEY_ID: s3-access-key
      AWS_SECRET_ACCESS_KEY: s3-secret-key
      S3_BUCKET: opendungeon

  valkey:
    image: valkey/valkey-bundle:latest
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/data
    environment:
      VALKEY_EXTRA_FLAGS: "--user user on >password ~* &* +@all"

  opendungeon:
    image: opendungeon:local
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - s3
      - valkey
    environment:
      AWS_ACCESS_KEY_ID: s3-access-key
      AWS_SECRET_ACCESS_KEY: s3-secret-key
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: opendungeon
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      S3_BUCKET: opendungeon
      S3_URL: http://s3:8333
      VALKEY_HOST: valkey:6379
      VALKEY_USER: user
      VALKEY_PASSWORD: password

volumes:
  postgres_data:
  s3_data:
  s3_filer:
  valkey_data:
