/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LevelEditorRouteImport } from './routes/level-editor'
import { Route as IndexRouteImport } from './routes/index'

const LevelEditorRoute = LevelEditorRouteImport.update({
  id: '/level-editor',
  path: '/level-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/level-editor': typeof LevelEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/level-editor': typeof LevelEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/level-editor': typeof LevelEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/level-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/level-editor'
  id: '__root__' | '/' | '/level-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelEditorRoute: typeof LevelEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/level-editor': {
      id: '/level-editor'
      path: '/level-editor'
      fullPath: '/level-editor'
      preLoaderRoute: typeof LevelEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelEditorRoute: LevelEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
