/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as MapbuilderRouteImport } from "./routes/mapbuilder";
import { Route as IndexRouteImport } from "./routes/index";

const MapbuilderRoute = MapbuilderRouteImport.update({
  id: "/mapbuilder",
  path: "/mapbuilder",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/mapbuilder": typeof MapbuilderRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/mapbuilder": typeof MapbuilderRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/mapbuilder": typeof MapbuilderRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/mapbuilder";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/mapbuilder";
  id: "__root__" | "/" | "/mapbuilder";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MapbuilderRoute: typeof MapbuilderRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/mapbuilder": {
      id: "/mapbuilder";
      path: "/mapbuilder";
      fullPath: "/mapbuilder";
      preLoaderRoute: typeof MapbuilderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapbuilderRoute: MapbuilderRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
