name: Tidy

on: [push]

jobs:
  tidy:
    name: Check Formatting and Tidiness
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.26.x
      - name: Run go fmt
        run: |
          output=$(gofmt -l .)
          if [ -n "$output" ]; then
            echo "The following files are not formatted:"
            echo "$output"
            exit 1
          fi
      - name: Run go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
